# environment.yaml

name: test-env-bachelor2
channels:
  - conda-forge
dependencies:
  - python>=3.5
  - anaconda
  - pip
  - pip:
    - -r file:/home/stu236894/Desktop/Bachelor-Arbeit-Chess/requirements.txt
