SEQ_LEN_FUTURE = 1
NUM_OUTPUT_PARAMETERS = 1
SEQ_LEN_PAST = 73
NUM_INPUT_PARAMETERS = 1

GPU_STRING = '/gpu:0'
BATCH_SIZE = 10000
MODEL_NAME = "Mlp"
EPOCHS = 300
STEPS_PER_EPOCH = 100 # 30
VALIDATION_STEPS = 20
THREADS = 10

#DATA_PATH = ".\src\supervised_engines\stockfish_DB.db"
DATA_PATH = ".\src\supervised_engines\lpha_beta_DB.db"