all:
	gcc -Ofast ../chess_implementationC/chess_board.c test_call.c nnue_eval.c ./nnue/nnue.cpp ./nnue/misc.cpp -o test_call


debug:
	gcc ../chess_implementationC/chess_board.c test_call.c nnue_eval.c ./nnue/nnue.cpp ./nnue/misc.cpp -o test_call